services:
  blue:
    build: ./blue
    container_name: blue
  green:
    build: ./green
    container_name: green
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - blue
      - green