name: Blue Green Deployment

on:
  push:
    tags:
      - "v*"

env:
  SSH_PRIVATE_KEY: ${{secrets.SSH_KEY}}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create SSH key
        run: |
          echo "${SSH_PRIVATE_KEY}" > vockey.pem
          chmod 400 vockey.pem

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{env.DOCKER_USERNAME}}
          password: ${{env.DOCKER_PASSWORD}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./deploy
          file: ./deploy/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/blue_green:${{github.ref_name}}


    